import type {
  CaseDetail,
  CaseListItem,
  DecisionResponse,
  DraftResponse,
  EvidenceGapResponse,
  EvidenceItem,
  EvidencePacketResponse,
  Page,
  ScoreResponse,
  SimulationResponse,
} from '../api/types'

export const CASE_LIST_ITEM: CaseListItem = {
  dispute_id: 'DSP-031597',
  reason_code: 'goods_not_received',
  status: 'closed',
  dispute_amount: '27531.38',
  created_at: '2026-10-14T11:07:00Z',
  response_deadline: '2026-10-28T11:07:00Z',
  scenario_archetype: 'high_value_strong',
  split: 'train',
}

export const CASE_PAGE: Page<CaseListItem> = {
  items: [
    CASE_LIST_ITEM,
    { ...CASE_LIST_ITEM, dispute_id: 'DSP-041961', reason_code: 'unauthorized_transaction', dispute_amount: '3890.35' },
  ],
  total: 50000,
  page: 1,
  page_size: 20,
}

export const CASE_DETAIL: CaseDetail = {
  ...CASE_LIST_ITEM,
  transaction: {
    transaction_id: 'TXN-031597',
    merchant_id: 'MERCH-0039',
    amount: '27531.38',
    currency: 'INR',
    payment_method: 'upi',
    created_at: '2026-08-31T11:00:00Z',
    captured_at: '2026-08-31T11:07:00Z',
    status: 'captured',
    device_id: 'DEV-1313456352',
    ip_address: '196.31.40.152',
    billing_address_id: 'ADDR-6154829',
    shipping_address_id: 'ADDR-6154829',
    avs_result: 'Y',
    cvv_result: 'M',
    three_ds_authenticated: true,
  },
  customer: {
    customer_id: 'CUST-012494',
    account_created_at: '2026-04-19T12:00:00Z',
    country: 'AE',
    account_age_days: 135,
    previous_order_count: 5,
    previous_successful_order_count: 4,
    previous_dispute_count: 0,
    previous_refund_count: 0,
  },
}

export const EVIDENCE_LIST: EvidenceItem[] = [
  {
    evidence_id: 'EVD-0081597',
    evidence_type: 'avs',
    available: true,
    value: { result: 'Y' },
    relevance: 'low',
    strength: 0.6973,
    created_at: '2026-10-13T11:07:00Z',
  },
  {
    evidence_id: 'EVD-0091597',
    evidence_type: 'proof_of_delivery',
    available: false,
    value: null,
    relevance: 'high',
    strength: 0,
    created_at: '2026-10-13T11:07:00Z',
  },
]

export const SCORE_RESPONSE: ScoreResponse = {
  case_id: 'DSP-031597',
  model_version: 'risk-v1',
  feature_schema_version: 'features-v1',
  reason_code: 'goods_not_received',
  raw_probability: 0.96784,
  calibrated_probability: 0.968005,
  risk_band: 'HIGH_WINNABILITY',
  calibration_method: 'sigmoid',
  top_positive_factors: [
    { feature: 'strong_evidence_count', contribution: 1.471977, value: 14, description: '14 evidence items are strong.' },
  ],
  top_negative_factors: [
    {
      feature: 'ev_proof_of_delivery_strength',
      contribution: -0.034062,
      value: 0,
      description: 'Proof of delivery evidence has a strength of 0.00.',
    },
  ],
  evidence_summary: {
    total: 16,
    available: 14,
    strong: 14,
    high_relevance_total: 5,
    high_relevance_available: 4,
    missing_key_types: ['proof_of_delivery'],
  },
  disclaimer: 'Winnability probability only. This is decision SUPPORT, not a recommendation to contest.',
}

export function makeDecision(overrides: Partial<DecisionResponse> = {}): DecisionResponse {
  return {
    case_id: 'DSP-031597',
    model_version: 'risk-v1',
    feature_schema_version: 'features-v1',
    decision_policy_version: 'decision-v1',
    reason_code: 'goods_not_received',
    decision: 'CONTEST',
    reason: 'Expected recovery materially exceeds estimated contest cost.',
    evidence_gap_downgrade: false,
    calibrated_probability: 0.968005,
    risk_band: 'HIGH_WINNABILITY',
    dispute_amount: 8500,
    recovery_rate: 1.0,
    recoverable_amount: 8500,
    contest_cost: 300,
    expected_recovery: 8228,
    expected_net_value: 7928,
    break_even_probability: 0.0353,
    break_even_explanation: 'At current assumptions, this case becomes economically positive above a 3.5% win probability.',
    sensitivity: [
      { probability: 0.868, delta: -0.1, expected_recovery: 7378, expected_net_value: 7078 },
      { probability: 0.968, delta: 0, expected_recovery: 8228, expected_net_value: 7928 },
    ],
    top_positive_factors: SCORE_RESPONSE.top_positive_factors,
    top_negative_factors: SCORE_RESPONSE.top_negative_factors,
    evidence_summary: SCORE_RESPONSE.evidence_summary,
    disclaimer: 'Decision support only, not an instruction to act.',
    ...overrides,
  }
}

export const EVIDENCE_GAP_RESPONSE: EvidenceGapResponse = {
  case_id: 'DSP-031597',
  reason_code: 'goods_not_received',
  schema_version: 'evidence-v1',
  coverage: { required: 4, available: 3, missing: 1 },
  coverage_ratio: 0.75,
  items: [
    {
      evidence_type: 'proof_of_delivery',
      required: true,
      status: 'MISSING',
      relevance: 'HIGH',
      priority: 'CRITICAL',
      reason: 'Proof of delivery is required to rebut a goods-not-received claim.',
      source_id: 'reason-code-guidance:goods_not_received',
      strength: 0,
      evidence_id: null,
    },
    {
      evidence_type: 'avs',
      required: true,
      status: 'AVAILABLE',
      relevance: 'LOW',
      priority: 'OPTIONAL',
      reason: 'AVS match supports authenticity of the original order.',
      source_id: 'reason-code-guidance:goods_not_received',
      strength: 0.6973,
      evidence_id: 'EVD-0081597',
    },
  ],
}

export const EVIDENCE_PACKET_RESPONSE: EvidencePacketResponse = {
  case_id: 'DSP-031597',
  schema_version: 'evidence-v1',
  generated_at: '2026-10-14T12:00:00Z',
  reason_code: 'goods_not_received',
  dispute_amount: 27531.38,
  dispute_status: 'closed',
  transaction: {
    payment_method: 'upi',
    transaction_status: 'captured',
    three_ds_authenticated: true,
    avs_result: 'Y',
    cvv_result: 'M',
  },
  customer: {
    account_age_days: 135,
    previous_order_count: 5,
    previous_successful_order_count: 4,
    previous_dispute_count: 0,
    previous_refund_count: 0,
  },
  evidence: [
    {
      evidence_id: 'EVD-0081597',
      evidence_type: 'avs',
      available: true,
      value: { result: 'Y' },
      relevance: 'low',
      strength: 0.6973,
      claim_type: 'fact',
    },
  ],
  gap: EVIDENCE_GAP_RESPONSE,
  guidance: {
    reason_code_id: 'goods_not_received',
    reason_code_name: 'Goods Not Received',
    description: 'Rebut with proof of delivery, tracking, or fulfillment confirmation.',
    source_id: 'reason-code-guidance:goods_not_received',
    claim_type: 'reference',
  },
}

export function makeDraft(overrides: Partial<DraftResponse> = {}): DraftResponse {
  return {
    case_id: 'DSP-031597',
    reason_code: 'goods_not_received',
    model_version: 'risk-v1',
    feature_schema_version: 'features-v1',
    decision_policy_version: 'decision-v1',
    evidence_schema_version: 'evidence-v1',
    knowledge_base_version: 'knowledge-v1',
    prompt_version: 'prompt-v1.1',
    response_schema_version: 'response-v1',
    verifier_version: 'verifier-v1.1',
    decision: {
      decision: 'CONTEST',
      calibrated_probability: 0.968005,
      expected_net_value: 7928,
      risk_band: 'HIGH_WINNABILITY',
    },
    evidence_gap: EVIDENCE_GAP_RESPONSE,
    retrieved_sources: [
      {
        chunk_id: 'CHUNK-001',
        text: 'For goods-not-received disputes, provide proof of delivery or tracking confirmation.',
        source_id: 'reason-code-guidance:goods_not_received',
        source_name: 'Goods Not Received Guidance',
        source_url: 'internal://knowledge/goods_not_received',
        relevance_score: 0.91,
        metadata: {
          doc_type: 'reason_code_guidance',
          reason_code_id: 'goods_not_received',
          evidence_type: 'proof_of_delivery',
          relevance: 'HIGH',
          addresses_gap: true,
        },
      },
    ],
    generation_available: true,
    summary: 'Draft rebuttal for a goods-not-received dispute.',
    claims: [
      {
        claim_id: 'CLAIM-1',
        text: 'The customer authenticated the transaction via 3-D Secure.',
        claim_type: 'fact',
        evidence_ids: ['EVD-0081597'],
        source_ids: ['reason-code-guidance:goods_not_received'],
      },
    ],
    missing_evidence: ['proof_of_delivery'],
    response_body: 'The transaction was authenticated via 3-D Secure and the AVS result matched.',
    claim_verifications: [
      {
        claim_id: 'CLAIM-1',
        status: 'SUPPORTED',
        evidence_ids: ['EVD-0081597'],
        source_ids: ['reason-code-guidance:goods_not_received'],
        explanation: 'AVS evidence on file supports this claim.',
        verifier_version: 'verifier-v1.1',
      },
    ],
    response_state: 'DRAFT_READY',
    response_state_reason: 'All claims were supported by evidence on file.',
    trace: {
      case_id: 'DSP-031597',
      decision: 'CONTEST',
      model_version: 'risk-v1',
      feature_schema_version: 'features-v1',
      decision_policy_version: 'decision-v1',
      evidence_schema_version: 'evidence-v1',
      knowledge_base_version: 'knowledge-v1',
      retrieval_config_version: 'retrieval-v1',
      prompt_version: 'prompt-v1.1',
      response_schema_version: 'response-v1',
      verifier_version: 'verifier-v1.1',
      retrieved_source_ids: ['reason-code-guidance:goods_not_received'],
      retrieved_chunk_ids: ['CHUNK-001'],
      cited_evidence_ids: ['EVD-0081597'],
      claim_count: 1,
      claim_statuses: { SUPPORTED: 1 },
      response_state: 'DRAFT_READY',
      generated_at: '2026-10-14T12:05:00Z',
    },
    disclaimer: 'AI-assisted draft. An analyst must review before use.',
    ...overrides,
  }
}

export function makeSimulation(overrides: Partial<SimulationResponse> = {}): SimulationResponse {
  return {
    simulation_id: 'SIM-abc123def456',
    is_simulation: true,
    reason_code: 'goods_not_received',
    score: {
      raw_probability: 0.9612,
      calibrated_probability: 0.9633,
      risk_band: 'HIGH_WINNABILITY',
      calibration_method: 'sigmoid',
      top_positive_factors: SCORE_RESPONSE.top_positive_factors,
      top_negative_factors: SCORE_RESPONSE.top_negative_factors,
      evidence_summary: SCORE_RESPONSE.evidence_summary,
    },
    decision: {
      decision: 'CONTEST',
      reason: 'Expected recovery materially exceeds estimated contest cost.',
      decision_policy_version: 'decision-v1',
      evidence_gap_downgrade: false,
      dispute_amount: 25000,
      recovery_rate: 1.0,
      recoverable_amount: 25000,
      contest_cost: 300,
      expected_recovery: 24082.8,
      expected_net_value: 23782.8,
      break_even_probability: 0.012,
      break_even_explanation: 'This scenario becomes economically positive above a 1.2% win probability.',
      sensitivity: [{ probability: 0.9633, delta: 0, expected_recovery: 24082.8, expected_net_value: 23782.8 }],
    },
    evidence_gap: EVIDENCE_GAP_RESPONSE,
    retrieved_sources: makeDraft().retrieved_sources,
    generation: null,
    trace: {
      simulation_id: 'SIM-abc123def456',
      model_version: 'risk-v1',
      feature_schema_version: 'features-v1',
      decision_policy_version: 'decision-v1',
      evidence_schema_version: 'evidence-v1',
      knowledge_base_version: 'knowledge-v1',
      retrieval_config_version: 'retrieval-v1',
      prompt_version: null,
      response_schema_version: null,
      verifier_version: null,
      retrieved_source_ids: ['reason-code-guidance:goods_not_received'],
      retrieved_chunk_ids: ['CHUNK-001'],
      generated_at: '2026-09-03T18:00:00Z',
      persisted: false,
    },
    disclaimer:
      'Scenario analysis on a hypothetical dispute. Not a real case, not persisted, and not a recommendation to act.',
    ...overrides,
  }
}
