/**
 * ============================================================================
 *  DEV-ONLY MOCK -- src/api/devDecisionMock.ts
 * ============================================================================
 *
 * This module exists SOLELY so the frontend can be developed and demoed
 * against a backend that has not yet deployed Phase 3's real /decision
 * endpoint. It is NOT the real decision engine and must never be mistaken
 * for one.
 *
 * Guarantees:
 *   - Only ever invoked from decisions.ts, and only when
 *     `import.meta.env.DEV` is true (i.e. structurally impossible in a
 *     production build, regardless of any env flag left set by mistake).
 *   - Same TypeScript interface as the real DecisionResponse (see
 *     api/types.ts), so callers/components never branch on "is this a mock".
 *   - Every mock response is unambiguously labeled: `reason` and
 *     `decision_policy_version` both carry a "[DEV MOCK]" marker, and
 *     decisions.ts additionally tags the result with `source: 'mock'` so the
 *     UI can render a visible "DEV MOCK" badge (see DecisionSourceBadge).
 *   - Does NOT reimplement the Phase 3 expected-value policy. It derives a
 *     plausible-looking placeholder from the case's REAL /score response
 *     (also fetched from the real backend) using a trivial, obviously-fake
 *     rule -- not decision-v1's actual thresholds/logic.
 *   - Deterministic per case_id (no Math.random()), so repeated views during
 *     a dev session are stable.
 *
 * DELETE THIS FILE once the real /decision endpoint is always available and
 * decisions.ts no longer needs a fallback path.
 */

import type { DecisionResponse, ScoreResponse } from './types'

const MOCK_CONTEST_COST = 300
const MOCK_RECOVERY_RATE = 1.0
const MOCK_MARKER = '[DEV MOCK]'

function toAmount(scoreCaseId: string): number {
  // Deterministic pseudo-amount from the case id string, purely so the mock
  // has *some* stable number to show -- real amount comes from /cases in the
  // real flow, this file has no access to it by design (kept minimal).
  let hash = 0
  for (let i = 0; i < scoreCaseId.length; i += 1) {
    hash = (hash * 31 + scoreCaseId.charCodeAt(i)) >>> 0
  }
  return 500 + (hash % 20000)
}

export async function mockDecideCase(
  caseId: string,
  score: ScoreResponse,
  disputeAmount?: number,
): Promise<DecisionResponse> {
  const probability = score.calibrated_probability
  const amount = disputeAmount ?? toAmount(caseId)
  const recoverable = amount * MOCK_RECOVERY_RATE
  const expectedRecovery = probability * recoverable
  const expectedNetValue = expectedRecovery - MOCK_CONTEST_COST
  const breakEven = recoverable > 0 ? MOCK_CONTEST_COST / recoverable : null

  let decision: DecisionResponse['decision']
  let reason: string
  if (expectedNetValue > 50 && probability >= 0.65) {
    decision = 'CONTEST'
    reason = `${MOCK_MARKER} Placeholder rule: expected net value is positive and P(win) is high. This is NOT the real decision-v1 policy.`
  } else if (expectedNetValue < -50 && probability <= 0.35) {
    decision = 'DO_NOT_CONTEST'
    reason = `${MOCK_MARKER} Placeholder rule: expected net value is negative and P(win) is low. This is NOT the real decision-v1 policy.`
  } else {
    decision = 'HUMAN_REVIEW'
    reason = `${MOCK_MARKER} Placeholder rule: case is near the mock boundary. This is NOT the real decision-v1 policy.`
  }

  return {
    case_id: caseId,
    model_version: score.model_version,
    feature_schema_version: score.feature_schema_version,
    decision_policy_version: `${MOCK_MARKER} mock-policy-v0`,
    reason_code: score.reason_code,
    decision,
    reason,
    evidence_gap_downgrade: false,
    calibrated_probability: probability,
    risk_band: score.risk_band,
    dispute_amount: amount,
    recovery_rate: MOCK_RECOVERY_RATE,
    recoverable_amount: recoverable,
    contest_cost: MOCK_CONTEST_COST,
    expected_recovery: expectedRecovery,
    expected_net_value: expectedNetValue,
    break_even_probability: breakEven,
    break_even_explanation:
      breakEven === null
        ? `${MOCK_MARKER} Undefined: recoverable amount is zero.`
        : `${MOCK_MARKER} Placeholder break-even estimate; not from the real decision engine.`,
    sensitivity: [-0.1, -0.05, 0, 0.05, 0.1].map((delta) => {
      const p = Math.min(1, Math.max(0, probability + delta))
      const recovery = p * recoverable
      return {
        probability: p,
        delta,
        expected_recovery: recovery,
        expected_net_value: recovery - MOCK_CONTEST_COST,
      }
    }),
    top_positive_factors: score.top_positive_factors,
    top_negative_factors: score.top_negative_factors,
    evidence_summary: score.evidence_summary,
    disclaimer: `${MOCK_MARKER} This decision was generated by a local development placeholder, not the real DisputeWise decision engine. No dispute is submitted, contested, or acted upon automatically.`,
  }
}
